stages:
  - push_to_test
#  - update_test_deployment  # That's temporary. Will be managed externally.

variables:
  PIDIO_ECR: "603927123425.dkr.ecr.eu-west-1.amazonaws.com/${CI_PROJECT_NAME}"
  PIDIO_GCR: "us-docker.pkg.dev/plainid-ci/plainid/${CI_PROJECT_NAME}"
  DOCKER_HOST: tcp://localhost:2375  # Relates to https://gitlab.com/gitlab-org/gitlab-foss/issues/65511
  DOCKER_TLS_CERTDIR: ''

push_to_test:
  image: docker:18.09.7-dind
  services:
    - docker:18-dind
  stage: push_to_test
  before_script:
    # GCP :: Login to Google Container Artifact Registry
    - echo ${GCP_SA_KEY} | base64 -d | docker login -u _json_key --password-stdin https://us-docker.pkg.dev
  script:
    - apk update
    - apk add python3 py3-pip
    - pip3 install awscli
    - aws configure set aws_access_key_id ${PIDIO_K8S_ACCESS_KEY}
    - aws configure set aws_secret_access_key ${PIDIO_K8S_ACCESS_SECRET}
    - aws configure set default.region eu-west-1
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - export BRANCH_NAME=$(echo $CI_COMMIT_BRANCH | sed -E "s/(_|@|\/)/-/g")
    # AWS :: Create an image with a new tag for ECR Registry
    - docker build -t "${PIDIO_ECR}:${BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}" .
    # AWS :: Push image to ECR Registry
    - docker push "${PIDIO_ECR}:${BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}"
    # GCP :: Add a new tag image for GCR Artifact Registry
    - docker tag "${PIDIO_ECR}:${BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}" "${PIDIO_GCR}:${BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}"
    # GCP :: Push image to GCR Artifact Registry
    - docker push "${PIDIO_GCR}:${BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}"


#update_test_deployment:
#  image: dtzar/helm-kubectl
#  stage: update_test_deployment
#  dependencies:
#    - push_to_test
#  script:
#    - apk add --no-cache curl jq python3 py-pip
#    - pip install awscli
#    - aws configure set aws_access_key_id ${PIDIO_K8S_ACCESS_KEY}
#    - aws configure set aws_secret_access_key ${PIDIO_K8S_ACCESS_SECRET}
#    - aws configure set default.region us-east-2
#    - aws eks update-kubeconfig --name partner-mgmt-staging
#    - kubectl -n default set image deployment/automation-reports maven=${TEST_ECR}:${CI_COMMIT_SHA}
